### ISSUE TITLE
сипиэн крашит

### ISSUE THREAD

**Issue by epicbattle1** [KisSsArt/KisSsArt.github.io#1]
когда чит пофиксят уже

**Comment by KisSsArt** [comment]
пошол нахуй нуб

**Comment by epicbattle1** [comment]
> 
> 
> пошол нахуй нуб

иди в пизду
уродина

**Comment by KisSsArt** [comment]
тапнул тебя в атоме изи

**Comment by epicbattle1** [comment]
когда краши пофиксят уже ну бооооооожеееееееее

**Comment by KisSsArt** [comment]
а че закрыл то
